# Generated by Django 5.2.8 on 2025-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pr',
            fields=[
                ('pid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('pName', models.CharField(max_length=30)),
                ('cost', models.FloatField()),
                ('creview', models.FloatField()),
                ('Deliverydate', models.DateTimeField()),
                ('company', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
